name: JSON to DotEnv
author: Sam Anthony

inputs:
  input-json:
    required: true
  output-dotenv:
    required: true

runs:
  using: "composite"
  steps:
    - name: JSON to DotEnv
      shell: bash
      run: |
        cat ${{ inputs.input-json }} | jq -r  '. | to_entries | map("\(.key)=\(.value)") | .[]' >> ${{ inputs.output-dotenv }}