name: PHP Composer with Cache
author: Sam Anthony

inputs:
  input-json:
    required: true
  output-dotenv:
    required: true

runs:
  using: "composite"
  steps:
    - name: JSON to DotEnv
      shell: bash
      run: |
        cp ${{ inputs.input-json }} ${{ inputs.output-dotenv }}