name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Automated test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JSON to DotEnv
        uses: the-pistol/github-action-json-to-dotenv@master
        id: abc
        with:
          input-json: '.github/workflows/test-1.json'
          output-dotenv: '.github/workflows/dotenv'

      - name: dump generated DotEnv file
        shell: bash
        run: |
          cat .github/workflows/dotenv      

      - name: Parse/use generated DotEnv file
        shell: bash
        run: |
          source .github/workflows/dotenv
          echo "var1:"
          echo $var1