name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JSON to DotEnv
        uses: the-pistol/github-action-json-to-dotenv@master
        with:
          input-json: '.github/workflows/test-1.json'
          output-dotenv: '.github/workflows/test-dotevn'
      - name: Show output
        run: |
          cat .github/workflows/test-dotevn