name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Automated test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JSON to DotEnv
        uses: the-pistol/github-action-json-to-dotenv@master
        id: json-dotenv
        with:
          input-json: '.github/workflows/test-1.json'
      - name: Show results
        run: |
          echo "var1:"
          echo "${{ steps.json-dotenv.outputs.var1 }}"
          echo "var2:"
          echo "${{ steps.json-dotenv.outputs.var2 }}"

                    